### PR TITLE
Aesthetic changes to wdl2dot script

### PR DESCRIPTION
**Pull request by yfarjoun**
- added color background to scatter blocks
- colors "primary" nodes and "terminal" nodes differently (nodes that have no input/output)

### CODE REVIEW

**Comment by yfarjoun** [comment]
@scottfrazer who should look at this? @meganshand is out...

**Comment by scottfrazer** [comment]
Looks good to me!

**Comment by yfarjoun** [comment]
I'm going to merge this. @meganshand, when you come back, I'll be happy to discuss color/aesthetic choices to which I'm absolutely not married!

**Comment by scottfrazer** [comment]
I published 1.0.22 to PyPI with this change

**Comment by meganshand** [comment]
Looks beautiful!

**Pull request merged**
